### ISSUE TITLE
Should document body be trimmed?

### ISSUE THREAD

**Issue by Arcesilas** [spatie/yaml-front-matter#11]
Since many text editors always add a new line at the end of the file, should the body be trimmed to remove trailing white spaces which are useless?

It does not change anything when displaying HTML, but this may not be the only purpose of documents with front matter.

**Comment by sebastiandedeyne** [comment]
Gonna leave this as is, since it doesn't matter when using html. Also, this package is agnostic of the language that the body is in, so maybe you're using something where it does matter.

In short, it doesn't add any immediate benefit, but it does add an extra step for us to maintain.
