### ISSUE TITLE
Remove illuminate/support dependency

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/yaml-front-matter#18]
We're using `illuminate/support` for the `Arr::get` method. It's not worth pulling in this dependency for that, as every Laravel upgrade forces us to allow the newer version.

**Comment by IvanBernatovic** [comment]
Hi, I'm interested in making a PR for this. The easiest approach is to copy `Arr` class and to strip it down only to the necessary methods so the `get` method can work properly. What do you think?

**Comment by freekmurze** [comment]
Sounds good.
